steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/thinkbots-frontend', '-f', 'Dockerfile.simple', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/thinkbots-frontend']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'thinkbots-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/thinkbots-frontend'
      - '--region'
      - 'me-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'REACT_APP_API_URL=https://thinkbots-backend-1045152789168.me-west1.run.app'

images:
  - 'gcr.io/$PROJECT_ID/thinkbots-frontend' 