import React, { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
}

const translations = {
  en: {
    loading: 'Loading...',
    error: 'Error',
    search: 'Search',
    filter: 'Filter',
    home: 'Home',
    dashboards: 'Dashboards',
    apiDashboard: 'API Dashboard',
    chatbot: 'Thinkbot',
    askMrC: 'Ask Mr. C',
    riskProgram: 'Risk Program',
    processMapping: 'Process Mapping',
    requirementMap: 'Requirement Map',
    nistFramework: 'AI-Powered Assistance Platform for NIST CSF 2.0',
    nistImplementation: 'Steering non-compliance to compliance',
    legislativeUpdates: 'Legislative Updates',
    complianceRequirements: 'Compliance Requirements',
    industryGuidelines: 'Industry Guidelines',
    riskManagement: 'Risk Management',
    incidentResponse: 'Incident Response',
    main: 'Main',
    assistance: 'Assistance',
    compliance: 'Compliance',
    cybersecurity: 'Cybersecurity',
    collaboration: 'Collaboration',
    aboutus: 'About Us',
    requirements: 'Requirements',
    nistGapAnalysis: 'NIST Gap Analysis',
    docAnonymity: 'Document Anonymity',
    teamCollab: 'Team Collaboration',
    aboutThinkbots: 'About Thinkbots',
    dashboard: 'Dashboard',
    assessment: 'Assessment',
    assignments: 'Assignments',
    nistResources: 'NIST CSF 2.0 Resources',
    thinkbotTitle: 'Thinkbot',
    thinkbotSubtitle: 'AI Assistant for NIST CSF 2.0',
    thinkbotPlaceholder: 'Ask about NIST CSF 2.0 requirements, implementation guidance, or best practices...',
    thinkbotHelper: 'Thinkbot can help you understand the NIST Cybersecurity Framework 2.0, including its requirements, implementation guidance, and best practices for cybersecurity risk management.',
    thinkbotDisclaimer: 'This chatbot is powered by AI and may not always provide accurate or up-to-date information. Please verify all information from official NIST sources. The end user is responsible for any actions taken based on the information provided.',
    thinkbotLoading: 'Loading NIST CSF 2.0 documentation...',
    thinkbotChatHistory: 'Chat History',
    thinkbotClearHistory: 'Clear History',
    thinkbotSend: 'Send',
    addRequirement: 'Add Requirement',
    requirementsOverview: 'Requirements Overview',
    totalRequirements: 'Total Requirements',
    compliant: 'Compliant',
    workInProgress: 'Work in Progress',
    nonCompliant: 'Non-Compliant',
    statusDistribution: 'Status Distribution',
    priorityDistribution: 'Priority Distribution',
    nistDomainDistribution: 'NIST Domain Distribution',
    nistCategoryDistribution: 'NIST Category Distribution',
    fortnightlyComplianceTrend: 'Fortnightly Compliance Trend',
    requirement: 'Requirement',
    nistDomain: 'NIST Domain',
    nistCategory: 'NIST Category',
    nistReference: 'NIST CSF 2.0 Reference',
    status: 'Status',
    priority: 'Priority',
    lastUpdated: 'Last Updated',
    lastUpdatedBy: 'Last Updated By',
    comments: 'Comments',
    actions: 'Actions',
    filterRequirement: 'Filter requirement...',
    filterNistDomain: 'Filter NIST Domain...',
    filterNistCategory: 'Filter NIST Category...',
    filterNistReference: 'Filter NIST Reference...',
    filterStatus: 'Filter status...',
    allNistDomains: 'All NIST Domains',
    allStatuses: 'All Statuses',
    edit: 'Edit',
    delete: 'Delete',
    close: 'Close',
    cancel: 'Cancel',
    save: 'Save',
    addApiConnection: 'Add API Connection',
    apiConnections: 'API Connections',
    noRequirementsData: 'No requirements data available. Please connect an API source or add custom requirements.',
    loadingRequirements: 'Loading requirements data...',
    analysisResults: 'Analysis Results',
    gapAnalysisDisclaimer: 'Disclaimer: The information provided through this gap analysis is evaluated by artificial intelligence and may be subject to errors or omissions. Please review all results carefully and consult with a compliance specialist for critical decisions.',
    gapAnalysisDescription: 'Select a NIST CSF 2.0 domain and upload your cybersecurity policy or procedure to assess its compliance. View gaps instantly and get actionable recommendations.',
    selectNistDomain: 'Select NIST CSF 2.0 Domain',
    uploadPolicy: 'Upload Document',
    uploadFile: 'Upload File',
    orDragAndDrop: 'or drag and drop',
    supportedFormats: 'Supported formats: PDF, DOC, DOCX, TXT',
    analyzing: 'Analyzing...',
    analyzeGaps: 'Analyze Document',
    gapAnalysisRecommendation1: 'Review all identified gaps and prioritize based on your organization\'s risk profile',
    gapAnalysisRecommendation2: 'Consult with cybersecurity experts to validate findings and recommendations',
    gapAnalysisRecommendation3: 'Develop an action plan to address critical gaps first',
    gapAnalysisRecommendation4: 'Regularly update your policies and procedures based on new requirements',
    gapAnalysisNote: 'This analysis is for guidance purposes only and should not replace professional compliance assessment.',
    enterNistControl: 'Enter NIST Control',
    enterNistControlPlaceholder: 'Enter the NIST CSF 2.0 control you want to analyze...',
    docAnonymityTitle: 'Doc Anonymity Tool',
    docAnonymitySubtitle: '(Non-AI)',
    docAnonymityDescription: 'Upload a document and provide a list of words or phrases to anonymize. The tool will mask those words with [MASKED] and let you download the anonymized document. The original file will be deleted after processing.',
    docAnonymityInfo: 'Documents uploaded here are securely processed and stored in Google Cloud (Australia region). This is a non-AI tool: it masks the specified words/phrases in your document, deletes the original upload, and keeps only the masked copy for you to download. Your data is handled securely and is not used for any other purpose.',
    docAnonymityWarning: 'You are responsible for specifying all sensitive or critical information you wish to mask. Please ensure you have entered all relevant words and phrases. If you miss any, you can retry the process as needed. Always review the masked PDF carefully before using it for AI analysis or sharing. The system will only mask the exact words/phrases you provide.',
    uploadDocument: 'Upload Document',
    uploadDocumentTitle: 'Upload your document',
    uploadDocumentPlaceholder: 'Choose a file to upload',
    wordsToMask: 'Words/Phrases to Mask (comma or newline separated)',
    wordsToMaskPlaceholder: 'e.g. John Doe, ACME Corp, confidential',
    performAnonymity: 'Perform Anonymity',
    processing: 'Processing...',
    downloadMaskedDocument: 'Download Masked Document',
    pleaseUploadDocument: 'Please upload a document and provide words/phrases to mask.',
    anonymizationFailed: 'Anonymization failed',
    anErrorOccurred: 'An error occurred',
    nistRequirementsTitle: 'NIST CSF 2.0 Requirements',
    criticalAiResponse: 'Thinkbots Response',
    checklistSelected: 'Checklist Selected:',
    generalNoChecklist: 'General / No Checklist selected',
    generatingResponse: 'Generating response...',
    selectRequirementMessage: 'Select a requirement and click the button to see the answer here.',
    askCriticalAi: 'Ask Thinkbots about this requirement',
    downloadAsPdf: 'Download as PDF',
    printOutput: 'Print Output',
    checklist: 'Checklist:',
    example: 'Example:',
    legalReference: 'Legal Reference:',
    sectors: 'Sectors:',
    complianceDeadline: 'Compliance Deadline:',
    reportingFrequency: 'Reporting Frequency:',
    switchToArabic: 'Switch to Arabic',
    switchToEnglish: 'Switch to English',
    logout: 'Logout',
    // Credits page translations
    creditsTitle: 'Thinkbots – Application Overview',
    creditsDescription: 'Thinkbots is a modern, AI-powered platform designed to help organizations understand, implement, and manage the NIST Cybersecurity Framework (CSF) 2.0. This application brings together advanced technology, user-friendly dashboards, and actionable insights to empower users in managing their cybersecurity posture.',
    secureCloudPlatform: 'Secure Cloud Platform',
    secureCloudDescription: 'Our application is hosted on a secure Google Cloud Platform, ensuring the highest standards of security and compliance for organizations. We maintain robust security controls and regular security assessments to protect your data.',
    keyFeatures: 'Key Features',
    strengths: 'Strengths',
    contactSupport: 'Contact & Support',
    contactDescription: 'For any questions, support, or to discuss your specific needs, please contact us at:'
  },
  ar: {
    loading: 'جاري التحميل...',
    error: 'خطأ',
    search: 'بحث',
    filter: 'تصفية',
    home: 'الرئيسية',
    dashboards: 'لوحات المعلومات',
    apiDashboard: 'لوحة معلومات API',
    chatbot: 'ثينكبوت',
    askMrC: 'اسأل السيد C',
    riskProgram: 'برنامج المخاطر',
    processMapping: 'رسم خرائط العمليات',
    requirementMap: 'خريطة المتطلبات',
    nistFramework: 'منصة المساعدة المدعومة بالذكاء الاصطناعي لـ NIST CSF 2.0',
    nistImplementation: 'توجيه عدم الامتثال إلى الامتثال',
    legislativeUpdates: 'التحديثات التشريعية',
    complianceRequirements: 'متطلبات الامتثال',
    industryGuidelines: 'المبادئ التوجيهية للصناعة',
    riskManagement: 'إدارة المخاطر',
    incidentResponse: 'الاستجابة للحوادث',
    main: 'الرئيسية',
    assistance: 'المساعدة',
    compliance: 'الامتثال',
    cybersecurity: 'الأمن السيبراني',
    collaboration: 'التعاون',
    aboutus: 'معلومات عنا',
    requirements: 'المتطلبات',
    nistGapAnalysis: 'تحليل فجوات NIST',
    docAnonymity: 'إخفاء هوية المستند',
    teamCollab: 'تعاون الفريق',
    aboutThinkbots: 'حول ثينكبوتس',
    dashboard: 'لوحة المعلومات',
    assessment: 'التقييم',
    assignments: 'المهام',
    nistResources: 'موارد إطار عمل NIST CSF 2.0',
    thinkbotTitle: 'ثينكبوت',
    thinkbotSubtitle: 'مساعد الذكاء الاصطناعي لإطار عمل NIST CSF 2.0',
    thinkbotPlaceholder: 'اسأل عن متطلبات NIST CSF 2.0 أو إرشادات التنفيذ أو أفضل الممارسات...',
    thinkbotHelper: 'ثينكبوت يمكنه مساعدتك في فهم إطار عمل NIST CSF 2.0، بما في ذلك متطلباته وإرشادات التنفيذ وأفضل ممارسات إدارة مخاطر الأمن السيبراني.',
    thinkbotDisclaimer: 'هذا الشات بوت مدعوم بالذكاء الاصطناعي وقد لا يقدم دائمًا معلومات دقيقة أو محدثة. يرجى التحقق من جميع المعلومات من مصادر NIST الرسمية. المستخدم النهائي مسؤول عن أي إجراءات يتم اتخاذها بناءً على المعلومات المقدمة.',
    thinkbotLoading: 'جاري تحميل وثائق NIST CSF 2.0...',
    thinkbotChatHistory: 'سجل المحادثة',
    thinkbotClearHistory: 'مسح السجل',
    thinkbotSend: 'إرسال',
    addRequirement: 'إضافة متطلب',
    requirementsOverview: 'نظرة عامة على المتطلبات',
    totalRequirements: 'إجمالي المتطلبات',
    compliant: 'متوافق',
    workInProgress: 'قيد التنفيذ',
    nonCompliant: 'غير متوافق',
    statusDistribution: 'توزيع الحالة',
    priorityDistribution: 'توزيع الأولوية',
    nistDomainDistribution: 'توزيع مجال NIST',
    nistCategoryDistribution: 'توزيع فئة NIST',
    fortnightlyComplianceTrend: 'اتجاه التوافق نصف الشهري',
    requirement: 'المتطلب',
    nistDomain: 'مجال NIST',
    nistCategory: 'فئة NIST',
    nistReference: 'مرجع NIST CSF 2.0',
    status: 'الحالة',
    priority: 'الأولوية',
    lastUpdated: 'آخر تحديث',
    lastUpdatedBy: 'تم التحديث بواسطة',
    comments: 'التعليقات',
    actions: 'الإجراءات',
    filterRequirement: 'تصفية المتطلب...',
    filterNistDomain: 'تصفية مجال NIST...',
    filterNistCategory: 'تصفية فئة NIST...',
    filterNistReference: 'تصفية مرجع NIST...',
    filterStatus: 'تصفية الحالة...',
    allNistDomains: 'جميع مجالات NIST',
    allStatuses: 'جميع الحالات',
    edit: 'تعديل',
    delete: 'حذف',
    close: 'إغلاق',
    cancel: 'إلغاء',
    save: 'حفظ',
    addApiConnection: 'إضافة اتصال API',
    apiConnections: 'اتصالات API',
    noRequirementsData: 'لا توجد بيانات متطلبات متاحة. يرجى الاتصال بمصدر API أو إضافة متطلبات مخصصة.',
    loadingRequirements: 'جاري تحميل بيانات المتطلبات...',
    gapAnalysisDisclaimer: 'تنويه: المعلومات المقدمة من خلال تحليل الفجوات هذا يتم تقييمها بواسطة الذكاء الاصطناعي وقد تكون عرضة للأخطاء أو النقص. يرجى مراجعة جميع النتائج بعناية واستشارة متخصص في الامتثال للقرارات الحاسمة.',
    gapAnalysisDescription: 'اختر مجال NIST CSF 2.0 وقم بتحميل سياسة الأمن السيبراني أو الإجراء الخاص بك لتقييم امتثاله. شاهد الفجوات على الفور واحصل على توصيات قابلة للتنفيذ.',
    selectNistDomain: 'اختر مجال NIST CSF 2.0',
    uploadPolicy: 'تحميل المستند',
    uploadFile: 'تحميل ملف',
    orDragAndDrop: 'أو اسحب وأفلت',
    supportedFormats: 'الصيغ المدعومة: PDF, DOC, DOCX, TXT',
    analyzing: 'جاري التحليل...',
    analyzeGaps: 'تحليل المستند',
    analysisResults: 'نتائج التحليل',
    gapAnalysisRecommendation1: 'راجع جميع الفجوات المحددة وحدد الأولويات بناءً على ملف المخاطر في مؤسستك',
    gapAnalysisRecommendation2: 'استشر خبراء الأمن السيبراني للتحقق من النتائج والتوصيات',
    gapAnalysisRecommendation3: 'طور خطة عمل لمعالجة الفجوات الحرجة أولاً',
    gapAnalysisRecommendation4: 'حدث سياساتك وإجراءاتك بانتظام بناءً على المتطلبات الجديدة',
    gapAnalysisNote: 'هذا التحليل للأغراض الإرشادية فقط ولا يجب أن يحل محل التقييم المهني للامتثال.',
    enterNistControl: 'أدخل ضابط NIST',
    enterNistControlPlaceholder: 'أدخل ضابط NIST CSF 2.0 الذي تريد تحليله...',
    docAnonymityTitle: 'أداة الإخفاء للمستند',
    docAnonymitySubtitle: '(بدون AI)',
    docAnonymityDescription: 'قم بتحميل مستند وإرفاق قائمة كلمات أو عبارات لإخفاءها. سيخفي الأداة هذه الكلمات باستخدام [MASKED] ويسمح لك بتحميل المستند الإخفاء بعد معالجته. سيتم حذف الملف الأصلي بعد المعالجة.',
    docAnonymityInfo: 'سيتم معالجة المستندات التي تحملها هنا بأمان وتخزينها في Google Cloud (منطقة أستراليا). هذه أداة ليس بها AI: يخفي الكلمات/العبارات المحددة في مستندك، حذف الملف الأصلي، ويحتفظ فقط بالنسخة المخفية لك لتحميلها. تتم معالجة البيانات بأمان ولا تستخدم لأي غرض آخر.',
    docAnonymityWarning: 'أنت مسؤول عن تحديد جميع المعلومات الحساسة أو المهمة التي تريد إخفاؤها. يرجى التأكد من إدخال جميع الكلمات والعبارات المتعلقة بالأمر قبل استخدام المستند المخفي. إذا نسيت أي منها، يمكنك إعادة المعالجة عند الضرورة. يرجى مراجعة المستند المخفي بعناية قبل استخدامه لتحليل AI أو مشاركته. سيخفي النظام الضبط الدقيق للكلمات/العبارات التي تقدمها لك فقط.',
    uploadDocument: 'تحميل المستند',
    uploadDocumentTitle: 'تحميل مستندك',
    uploadDocumentPlaceholder: 'اختر ملفًا لتحميله',
    wordsToMask: 'الكلمات/العبارات التي ستخفيها (مفصولة بفواصل أو سطر جديد)',
    wordsToMaskPlaceholder: 'مثال: John Doe, ACME Corp, المعلومات الحساسة',
    performAnonymity: 'إجراء الإخفاء',
    processing: 'جاري المعالجة...',
    downloadMaskedDocument: 'تحميل المستند المخفي',
    pleaseUploadDocument: 'يرجى تحميل مستند وإرفاق كلمات/العبارات التي ستخفيها.',
    anonymizationFailed: 'فشل الإخفاء',
    anErrorOccurred: 'حدث خطأ',
    nistRequirementsTitle: 'متطلبات NIST CSF 2.0',
    criticalAiResponse: 'استجابة ثينكبوتس',
    checklistSelected: 'القائمة المحددة:',
    generalNoChecklist: 'عام / لا يوجد قائمة مراجعة محددة',
    generatingResponse: 'جاري إنشاء الاستجابة...',
    selectRequirementMessage: 'حدد متطلب واضغط على الزر هنا لرؤية الإجابة.',
    askCriticalAi: 'اسأل ثينكبوتس عن هذا المتطلب',
    downloadAsPdf: 'تحميل كملف PDF',
    printOutput: 'طباعة الإخراج',
    checklist: 'القائمة المراجعة:',
    example: 'مثال:',
    legalReference: 'مرجع قانوني:',
    sectors: 'المجالات:',
    complianceDeadline: 'موعد الامتثال:',
    reportingFrequency: 'تكرار الإبلاغ:',
    switchToArabic: 'التبديل إلى العربية',
    switchToEnglish: 'التبديل إلى الإنجليزية',
    logout: 'تسجيل الخروج',
    // Credits page translations
    creditsTitle: 'ثينكبوتس – نظرة عامة على التطبيق',
    creditsDescription: 'ثينكبوتس هو منصة حديثة مدعومة بالذكاء الاصطناعي تهدف إلى مساعدة المؤسسات على فهم وتطبيق وإدارة إطار عمل الأمن السيبراني NIST CSF 2.0. يجمع هذا التطبيق بين التكنولوجيا المتقدمة ولوحات المعلومات سهلة الاستخدام والرؤى القابلة للتنفيذ لتمكين المستخدمين من إدارة وضعهم الأمني السيبراني.',
    secureCloudPlatform: 'منصة سحابية آمنة',
    secureCloudDescription: 'يستضيف تطبيقنا على منصة Google Cloud الآمنة، مما يضمن أعلى معايير الأمان والامتثال للمؤسسات. نحن نحافظ على ضوابط أمان قوية وتقييمات أمنية منتظمة لحماية بياناتك.',
    keyFeatures: 'الميزات الرئيسية',
    strengths: 'نقاط القوة',
    contactSupport: 'الاتصال والدعم',
    contactDescription: 'لأي استفسارات أو دعم أو لمناقشة احتياجاتك الخاصة، يرجى التواصل معنا عبر:'
  }
};

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const t = (key: string): string => {
    return translations[language as keyof typeof translations]?.[key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}; 