name: Deploy to Cloud Run

on:
  push:
    branches:
      - main  # Trigger on pushes to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: thinkbots-production
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Configure Docker for Google Cloud
      run: gcloud auth configure-docker

    - name: Build Docker image
      run: |
        docker build -t gcr.io/thinkbots-production/thinkbots-frontend .

    - name: Push Docker image to Container Registry
      run: |
        docker push gcr.io/thinkbots-production/thinkbots-frontend

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy thinkbots-frontend \
          --image gcr.io/thinkbots-production/thinkbots-frontend \
          --region me-west1 \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars REACT_APP_API_URL=https://thinkbots-backend-1045152789168.me-west1.run.app
