name: Deploy to Cloud Run (Dammam)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: thinkbots-production
          service_account_email: thinkbots-frontend@thinkbots-production.iam.gserviceaccount.com
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker to use Artifact Registry
        run: |
          gcloud auth configure-docker me-west1-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t me-west1-docker.pkg.dev/thinkbots-production/thinkbots-frontend-repo/thinkbots-frontend .

      - name: Authenticate Docker with Artifact Registry
        run: |
          gcloud auth print-access-token | docker login -u oauth2accesstoken --password-stdin https://me-west1-docker.pkg.dev

      - name: Push Docker image to Artifact Registry
        run: |
          docker push me-west1-docker.pkg.dev/thinkbots-production/thinkbots-frontend-repo/thinkbots-frontend

      - name: Deploy to Cloud Run (Dammam)
        run: |
          gcloud run deploy thinkbots-frontend \
            --image me-west1-docker.pkg.dev/thinkbots-production/thinkbots-frontend-repo/thinkbots-frontend \
            --region me-west1 \
            --platform managed \
            --allow-unauthenticated
